
package org.w3._2009._02.ws_tra;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "accessPointService", targetNamespace = "http://www.w3.org/2009/02/ws-tra", wsdlLocation = "file:./src/main/resources/wsdl_v2.0-client.wsdl")
public class AccessPointService
    extends Service
{

    private final static URL ACCESSPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.w3._2009._02.ws_tra.AccessPointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.w3._2009._02.ws_tra.AccessPointService.class.getResource(".");
            url = new URL(baseUrl, "file:./src/main/resources/wsdl_v2.0-client.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:./src/main/resources/wsdl_v2.0-client.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCESSPOINTSERVICE_WSDL_LOCATION = url;
    }

    public AccessPointService(URL wsdlLocation, QName serviceName, WebServiceFeature feature) {
        super(wsdlLocation, serviceName , feature);
    }

    
    public AccessPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessPointService() {
        super(ACCESSPOINTSERVICE_WSDL_LOCATION, new QName("http://www.w3.org/2009/02/ws-tra", "accessPointService"));
    }

    /**
     * 
     * @return
     *     returns Resource
     */
    @WebEndpoint(name = "ResourceBindingPort")
    public Resource getResourceBindingPort() {
        return super.getPort(new QName("http://www.w3.org/2009/02/ws-tra", "ResourceBindingPort"), Resource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Resource
     */
    @WebEndpoint(name = "ResourceBindingPort")
    public Resource getResourceBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.w3.org/2009/02/ws-tra", "ResourceBindingPort"), Resource.class, features);
    }

}
