
package org.w3._2009._02.ws_tra;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "StartException", targetNamespace = "http://busdox.org/2010/02/channel/fault")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StartException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMessage(String message, StartException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMessage(String message, StartException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.w3._2009._02.ws_tra.StartException
     */
    public StartException getFaultInfo() {
        return faultInfo;
    }

}
