//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.03 at 06:38:09 AM CEST 
//


package org.busdox.smp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EndpointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndpointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2005/08/addressing}EndpointReference"/>
 *         &lt;element name="RequireBusinessLevelSignature" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="MinimumAuthenticationLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceActivationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ServiceExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TechnicalContactUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="TechnicalInformationUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://busdox.org/serviceMetadata/publishing/1.0/}ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="transportProfile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointType", namespace = "http://busdox.org/serviceMetadata/publishing/1.0/", propOrder = {
    "endpointReference",
    "requireBusinessLevelSignature",
    "minimumAuthenticationLevel",
    "serviceActivationDate",
    "serviceExpirationDate",
    "certificate",
    "serviceDescription",
    "technicalContactUrl",
    "technicalInformationUrl",
    "extension"
})
public class EndpointType {

    @XmlElement(name = "EndpointReference", namespace = "http://www.w3.org/2005/08/addressing", required = true)
    protected EndpointReferenceType endpointReference;
    @XmlElement(name = "RequireBusinessLevelSignature")
    protected boolean requireBusinessLevelSignature;
    @XmlElement(name = "MinimumAuthenticationLevel")
    protected String minimumAuthenticationLevel;
    @XmlElement(name = "ServiceActivationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceActivationDate;
    @XmlElement(name = "ServiceExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceExpirationDate;
    @XmlElement(name = "Certificate", required = true)
    protected String certificate;
    @XmlElement(name = "ServiceDescription", required = true)
    protected String serviceDescription;
    @XmlElement(name = "TechnicalContactUrl", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String technicalContactUrl;
    @XmlElement(name = "TechnicalInformationUrl")
    @XmlSchemaType(name = "anyURI")
    protected String technicalInformationUrl;
    @XmlElement(name = "Extension")
    protected ExtensionType extension;
    @XmlAttribute(name = "transportProfile")
    protected String transportProfile;

    /**
     * Gets the value of the endpointReference property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointReferenceType }
     *     
     */
    public EndpointReferenceType getEndpointReference() {
        return endpointReference;
    }

    /**
     * Sets the value of the endpointReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointReferenceType }
     *     
     */
    public void setEndpointReference(EndpointReferenceType value) {
        this.endpointReference = value;
    }

    /**
     * Gets the value of the requireBusinessLevelSignature property.
     * 
     */
    public boolean isRequireBusinessLevelSignature() {
        return requireBusinessLevelSignature;
    }

    /**
     * Sets the value of the requireBusinessLevelSignature property.
     * 
     */
    public void setRequireBusinessLevelSignature(boolean value) {
        this.requireBusinessLevelSignature = value;
    }

    /**
     * Gets the value of the minimumAuthenticationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumAuthenticationLevel() {
        return minimumAuthenticationLevel;
    }

    /**
     * Sets the value of the minimumAuthenticationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumAuthenticationLevel(String value) {
        this.minimumAuthenticationLevel = value;
    }

    /**
     * Gets the value of the serviceActivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceActivationDate() {
        return serviceActivationDate;
    }

    /**
     * Sets the value of the serviceActivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceActivationDate(XMLGregorianCalendar value) {
        this.serviceActivationDate = value;
    }

    /**
     * Gets the value of the serviceExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceExpirationDate() {
        return serviceExpirationDate;
    }

    /**
     * Sets the value of the serviceExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceExpirationDate(XMLGregorianCalendar value) {
        this.serviceExpirationDate = value;
    }

    /**
     * Gets the value of the certificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * Sets the value of the certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificate(String value) {
        this.certificate = value;
    }

    /**
     * Gets the value of the serviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDescription() {
        return serviceDescription;
    }

    /**
     * Sets the value of the serviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDescription(String value) {
        this.serviceDescription = value;
    }

    /**
     * Gets the value of the technicalContactUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalContactUrl() {
        return technicalContactUrl;
    }

    /**
     * Sets the value of the technicalContactUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalContactUrl(String value) {
        this.technicalContactUrl = value;
    }

    /**
     * Gets the value of the technicalInformationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalInformationUrl() {
        return technicalInformationUrl;
    }

    /**
     * Sets the value of the technicalInformationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalInformationUrl(String value) {
        this.technicalInformationUrl = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the transportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportProfile() {
        return transportProfile;
    }

    /**
     * Sets the value of the transportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportProfile(String value) {
        this.transportProfile = value;
    }

}
