//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.03 at 06:38:09 AM CEST 
//


package org.busdox.smp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://busdox.org/transport/identifiers/1.0/}ProcessIdentifier"/>
 *         &lt;element name="ServiceEndpointList" type="{http://busdox.org/serviceMetadata/publishing/1.0/}ServiceEndpointList"/>
 *         &lt;element name="Extension" type="{http://busdox.org/serviceMetadata/publishing/1.0/}ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessType", namespace = "http://busdox.org/serviceMetadata/publishing/1.0/", propOrder = {
    "processIdentifier",
    "serviceEndpointList",
    "extension"
})
public class ProcessType {

    @XmlElement(name = "ProcessIdentifier", namespace = "http://busdox.org/transport/identifiers/1.0/", required = true)
    protected ProcessIdentifierType processIdentifier;
    @XmlElement(name = "ServiceEndpointList", required = true)
    protected ServiceEndpointList serviceEndpointList;
    @XmlElement(name = "Extension")
    protected ExtensionType extension;

    /**
     * Gets the value of the processIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessIdentifierType }
     *     
     */
    public ProcessIdentifierType getProcessIdentifier() {
        return processIdentifier;
    }

    /**
     * Sets the value of the processIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessIdentifierType }
     *     
     */
    public void setProcessIdentifier(ProcessIdentifierType value) {
        this.processIdentifier = value;
    }

    /**
     * Gets the value of the serviceEndpointList property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceEndpointList }
     *     
     */
    public ServiceEndpointList getServiceEndpointList() {
        return serviceEndpointList;
    }

    /**
     * Sets the value of the serviceEndpointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceEndpointList }
     *     
     */
    public void setServiceEndpointList(ServiceEndpointList value) {
        this.serviceEndpointList = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

}
